# -*- coding: utf-8 -*-
"""ASSOCIATION_RULE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y3WHkDrsT0ZRKd8q94HgTHZpuch0aC7n
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/Market_Basket_Optimisation.csv")

df

df.info()

df.isnull()

df.isnull().sum()

df.head()

df.tail()

transactions=[]
for i in range(0,len(df)):
  transactions.append([str(df.values[i,j])for j in range (0,20) if str(df.values[i,j])!='0'])

transactions

!pip install apyori

from apyori import apriori
rules=apriori(transactions=transactions,min_support=0.003,min_confidence=0.2,min_lift=3,min_length=2,max_length=2)

results=list(rules)
results

def inspect(results):
    lhs         = [tuple(result[2][0][0]) for result in results]
    rhs         = [tuple(result[2][0][1]) for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))


results_df = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])
print("Top 10 Association Rules:")
print(results_df.nlargest(n=10, columns='Lift'))

